### ISSUE TITLE
设置wrapper尺寸后，刻度尺的准确值会下降，误差会变大

### ISSUE THREAD

**Issue by xinzefeng** [chuxiaoguo/vue-sketch-ruler#4]
设置wrapper尺寸后，刻度尺的准确值会下降，误差会变大
![image](https://user-images.githubusercontent.com/23490547/79545991-35a25d80-80c4-11ea-999b-c86edf552a4d.png)
这个问题得如何配置呢？

**Comment by chuxiaoguo** [comment]
em ... 我看了这个问题，晚点我给出解决方案 ...

**Comment by chuxiaoguo** [comment]
该问题已经解决，参考最新的demo例子，[查看这里](https://github.com/chuxiaoguo/vue-sketch-ruler/blob/master/docs/src/components/UserRuler.vue)

**Comment by xinzefeng** [comment]
比如我想适配浏览器大小，进行resize宽度高度，让画布也跟随适配大小，要如何完成呢？ 我根据API试了下，没有成功

**Comment by chuxiaoguo** [comment]
进行resize响应的时候，更新initSize方法（该方法可以根据自己的需求优化） ... 。

**Comment by xinzefeng** [comment]
看到你新加的方法了，多谢回复。学习到了。
